//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by DDove Architecture bind. Do not edit.
// </auto-generated>
//------------------------------------------------------------------------------
using DDoveFramework.Core;

namespace Game
{
    public sealed class GameArchitecture : Architecture<GameArchitecture>
    {
        protected override void Init()
        {
        }
    }
}
