//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by DDove Architecture bind. Do not edit.
// </auto-generated>
//------------------------------------------------------------------------------
// BIND:Utility:global::Game.CfgUtility:global::Game.CfgUtility
// BIND:Model:global::Game.PlayerModel:global::Game.PlayerModel
// BIND:System:global::Game.PlayerSystem:global::Game.PlayerSystem
using DDoveFramework.Core;

namespace Game
{
    public sealed class GameArchitecture : Architecture<GameArchitecture>
    {
        protected override void Init()
        {
            RegisterUtility(new global::Game.CfgUtility());
            RegisterModel(new global::Game.PlayerModel());
            RegisterSystem(new global::Game.PlayerSystem());
        }
    }
}
