//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by DDove Architecture bind. Do not edit.
// </auto-generated>
//------------------------------------------------------------------------------
// BIND:Utility:global::Game.CfgUtility:global::Game.CfgUtility
using DDoveFramework.Core;

namespace Game
{
    public sealed class GameArchitecture : Architecture<GameArchitecture>
    {
        protected override void Init()
        {
            RegisterUtility(new global::Game.CfgUtility());
        }
    }
}
