//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by DDoveUI. Do not edit.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

namespace Game.UI
{
    public partial class WndCollectDemo
    {
    }
}
