//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by DDoveUI. Do not edit.
// </auto-generated>
//------------------------------------------------------------------------------
using DDoveFramework.Core;
using Game;

namespace Game.UI
{
    public partial class WndLoopHDemo : IController
    {
        public IArchitecture GetArchitecture() => GameArchitecture.Interface;
    }
}
